
// This file has been generated by the GUI designer. Do not modify.
namespace UltiCalcGUI
{
	public partial class IPNWindow
	{
		private global::Gtk.HBox hbox13;
		private global::Gtk.VBox vbox12;
		private global::Gtk.VBox vbox15;
		private global::Gtk.HBox hbox17;
		private global::Gtk.Button button7;
		private global::Gtk.Button button8;
		private global::Gtk.Button button9;
		private global::Gtk.HBox hbox18;
		private global::Gtk.Button button4;
		private global::Gtk.Button button5;
		private global::Gtk.Button button6;
		private global::Gtk.HBox hbox19;
		private global::Gtk.Button button1;
		private global::Gtk.Button button2;
		private global::Gtk.Button button3;
		private global::Gtk.Button buttonComma;
		private global::Gtk.VBox vbox13;
		private global::Gtk.Label output;
		private global::Gtk.VBox vbox14;
		private global::Gtk.HBox hbox15;
		private global::Gtk.Button button;
		private global::Gtk.Button buttonPlus;
		private global::Gtk.Button buttonMinus;
		private global::Gtk.HBox hbox14;
		private global::Gtk.Button buttonMultiply;
		private global::Gtk.Button buttonDivide;
		private global::Gtk.Button buttonModulus;
		private global::Gtk.Button buttonEnter;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget UltiCalcGUI.IPNWindow
			this.Name = "UltiCalcGUI.IPNWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("IPNWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child UltiCalcGUI.IPNWindow.Gtk.Container+ContainerChild
			this.hbox13 = new global::Gtk.HBox ();
			this.hbox13.Name = "hbox13";
			this.hbox13.Spacing = 6;
			// Container child hbox13.Gtk.Box+BoxChild
			this.vbox12 = new global::Gtk.VBox ();
			this.vbox12.Name = "vbox12";
			this.vbox12.Spacing = 6;
			// Container child vbox12.Gtk.Box+BoxChild
			this.vbox15 = new global::Gtk.VBox ();
			this.vbox15.Name = "vbox15";
			this.vbox15.Spacing = 6;
			// Container child vbox15.Gtk.Box+BoxChild
			this.hbox17 = new global::Gtk.HBox ();
			this.hbox17.Name = "hbox17";
			this.hbox17.Spacing = 6;
			// Container child hbox17.Gtk.Box+BoxChild
			this.button7 = new global::Gtk.Button ();
			this.button7.CanFocus = true;
			this.button7.Name = "button7";
			this.button7.UseUnderline = true;
			this.button7.Label = global::Mono.Unix.Catalog.GetString ("7");
			this.hbox17.Add (this.button7);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox17 [this.button7]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox17.Gtk.Box+BoxChild
			this.button8 = new global::Gtk.Button ();
			this.button8.CanFocus = true;
			this.button8.Name = "button8";
			this.button8.UseUnderline = true;
			this.button8.Label = global::Mono.Unix.Catalog.GetString ("8");
			this.hbox17.Add (this.button8);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox17 [this.button8]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox17.Gtk.Box+BoxChild
			this.button9 = new global::Gtk.Button ();
			this.button9.CanFocus = true;
			this.button9.Name = "button9";
			this.button9.UseUnderline = true;
			this.button9.Label = global::Mono.Unix.Catalog.GetString ("9");
			this.hbox17.Add (this.button9);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox17 [this.button9]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox15.Add (this.hbox17);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox15 [this.hbox17]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox15.Gtk.Box+BoxChild
			this.hbox18 = new global::Gtk.HBox ();
			this.hbox18.Name = "hbox18";
			this.hbox18.Spacing = 6;
			// Container child hbox18.Gtk.Box+BoxChild
			this.button4 = new global::Gtk.Button ();
			this.button4.CanFocus = true;
			this.button4.Name = "button4";
			this.button4.UseUnderline = true;
			this.button4.Label = global::Mono.Unix.Catalog.GetString ("4");
			this.hbox18.Add (this.button4);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox18 [this.button4]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox18.Gtk.Box+BoxChild
			this.button5 = new global::Gtk.Button ();
			this.button5.CanFocus = true;
			this.button5.Name = "button5";
			this.button5.UseUnderline = true;
			this.button5.Label = global::Mono.Unix.Catalog.GetString ("5");
			this.hbox18.Add (this.button5);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox18 [this.button5]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox18.Gtk.Box+BoxChild
			this.button6 = new global::Gtk.Button ();
			this.button6.CanFocus = true;
			this.button6.Name = "button6";
			this.button6.UseUnderline = true;
			this.button6.Label = global::Mono.Unix.Catalog.GetString ("6");
			this.hbox18.Add (this.button6);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox18 [this.button6]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			this.vbox15.Add (this.hbox18);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox15 [this.hbox18]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox15.Gtk.Box+BoxChild
			this.hbox19 = new global::Gtk.HBox ();
			this.hbox19.Name = "hbox19";
			this.hbox19.Spacing = 6;
			// Container child hbox19.Gtk.Box+BoxChild
			this.button1 = new global::Gtk.Button ();
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			this.button1.Label = global::Mono.Unix.Catalog.GetString ("1");
			this.hbox19.Add (this.button1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.button1]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox19.Gtk.Box+BoxChild
			this.button2 = new global::Gtk.Button ();
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			this.button2.UseUnderline = true;
			this.button2.Label = global::Mono.Unix.Catalog.GetString ("2");
			this.hbox19.Add (this.button2);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.button2]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox19.Gtk.Box+BoxChild
			this.button3 = new global::Gtk.Button ();
			this.button3.CanFocus = true;
			this.button3.Name = "button3";
			this.button3.UseUnderline = true;
			this.button3.Label = global::Mono.Unix.Catalog.GetString ("3");
			this.hbox19.Add (this.button3);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.button3]));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			this.vbox15.Add (this.hbox19);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox15 [this.hbox19]));
			w12.Position = 2;
			w12.Expand = false;
			w12.Fill = false;
			this.vbox12.Add (this.vbox15);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.vbox15]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox12.Gtk.Box+BoxChild
			this.buttonComma = new global::Gtk.Button ();
			this.buttonComma.CanFocus = true;
			this.buttonComma.Name = "buttonComma";
			this.buttonComma.UseUnderline = true;
			this.buttonComma.Label = global::Mono.Unix.Catalog.GetString (".");
			this.vbox12.Add (this.buttonComma);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.buttonComma]));
			w14.Position = 2;
			w14.Expand = false;
			w14.Fill = false;
			this.hbox13.Add (this.vbox12);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.vbox12]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child hbox13.Gtk.Box+BoxChild
			this.vbox13 = new global::Gtk.VBox ();
			this.vbox13.Name = "vbox13";
			this.vbox13.Spacing = 6;
			// Container child vbox13.Gtk.Box+BoxChild
			this.output = new global::Gtk.Label ();
			this.output.Name = "output";
			this.vbox13.Add (this.output);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.output]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox13.Gtk.Box+BoxChild
			this.vbox14 = new global::Gtk.VBox ();
			this.vbox14.Name = "vbox14";
			this.vbox14.Spacing = 6;
			// Container child vbox14.Gtk.Box+BoxChild
			this.hbox15 = new global::Gtk.HBox ();
			this.hbox15.Name = "hbox15";
			this.hbox15.Spacing = 6;
			// Container child hbox15.Gtk.Box+BoxChild
			this.button = new global::Gtk.Button ();
			this.button.CanFocus = true;
			this.button.Name = "button";
			this.button.UseUnderline = true;
			this.button.Label = global::Mono.Unix.Catalog.GetString ("0");
			this.hbox15.Add (this.button);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.button]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child hbox15.Gtk.Box+BoxChild
			this.buttonPlus = new global::Gtk.Button ();
			this.buttonPlus.CanFocus = true;
			this.buttonPlus.Name = "buttonPlus";
			this.buttonPlus.UseUnderline = true;
			this.buttonPlus.Label = global::Mono.Unix.Catalog.GetString ("+");
			this.hbox15.Add (this.buttonPlus);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.buttonPlus]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			// Container child hbox15.Gtk.Box+BoxChild
			this.buttonMinus = new global::Gtk.Button ();
			this.buttonMinus.CanFocus = true;
			this.buttonMinus.Name = "buttonMinus";
			this.buttonMinus.UseUnderline = true;
			this.buttonMinus.Label = global::Mono.Unix.Catalog.GetString ("-");
			this.hbox15.Add (this.buttonMinus);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.buttonMinus]));
			w19.Position = 2;
			w19.Expand = false;
			w19.Fill = false;
			this.vbox14.Add (this.hbox15);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.hbox15]));
			w20.Position = 0;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox14.Gtk.Box+BoxChild
			this.hbox14 = new global::Gtk.HBox ();
			this.hbox14.Name = "hbox14";
			this.hbox14.Spacing = 6;
			// Container child hbox14.Gtk.Box+BoxChild
			this.buttonMultiply = new global::Gtk.Button ();
			this.buttonMultiply.CanFocus = true;
			this.buttonMultiply.Name = "buttonMultiply";
			this.buttonMultiply.UseUnderline = true;
			this.buttonMultiply.Label = global::Mono.Unix.Catalog.GetString ("*");
			this.hbox14.Add (this.buttonMultiply);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.buttonMultiply]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			// Container child hbox14.Gtk.Box+BoxChild
			this.buttonDivide = new global::Gtk.Button ();
			this.buttonDivide.CanFocus = true;
			this.buttonDivide.Name = "buttonDivide";
			this.buttonDivide.UseUnderline = true;
			this.buttonDivide.Label = global::Mono.Unix.Catalog.GetString ("/");
			this.hbox14.Add (this.buttonDivide);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.buttonDivide]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			// Container child hbox14.Gtk.Box+BoxChild
			this.buttonModulus = new global::Gtk.Button ();
			this.buttonModulus.CanFocus = true;
			this.buttonModulus.Name = "buttonModulus";
			this.buttonModulus.UseUnderline = true;
			this.buttonModulus.Label = global::Mono.Unix.Catalog.GetString ("%");
			this.hbox14.Add (this.buttonModulus);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.buttonModulus]));
			w23.Position = 2;
			w23.Expand = false;
			w23.Fill = false;
			this.vbox14.Add (this.hbox14);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.hbox14]));
			w24.Position = 1;
			w24.Expand = false;
			w24.Fill = false;
			// Container child vbox14.Gtk.Box+BoxChild
			this.buttonEnter = new global::Gtk.Button ();
			this.buttonEnter.CanFocus = true;
			this.buttonEnter.Name = "buttonEnter";
			this.buttonEnter.UseUnderline = true;
			this.buttonEnter.Label = global::Mono.Unix.Catalog.GetString ("ENTER");
			this.vbox14.Add (this.buttonEnter);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.buttonEnter]));
			w25.Position = 2;
			w25.Fill = false;
			this.vbox13.Add (this.vbox14);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.vbox14]));
			w26.Position = 1;
			w26.Expand = false;
			w26.Fill = false;
			this.hbox13.Add (this.vbox13);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.vbox13]));
			w27.Position = 1;
			w27.Expand = false;
			w27.Fill = false;
			this.Add (this.hbox13);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 438;
			this.DefaultHeight = 300;
			this.Show ();
			this.button7.Clicked += new global::System.EventHandler (this.OnButton7Clicked);
			this.button8.Clicked += new global::System.EventHandler (this.OnButton8Clicked);
			this.button9.Clicked += new global::System.EventHandler (this.OnButton9Clicked);
			this.button4.Clicked += new global::System.EventHandler (this.OnButton4Clicked);
			this.button5.Clicked += new global::System.EventHandler (this.OnButton5Clicked);
			this.button6.Clicked += new global::System.EventHandler (this.OnButton6Clicked);
			this.button1.Clicked += new global::System.EventHandler (this.OnButton1Clicked);
			this.button2.Clicked += new global::System.EventHandler (this.OnButton2Clicked);
			this.button3.Clicked += new global::System.EventHandler (this.OnButton3Clicked);
			this.buttonComma.Clicked += new global::System.EventHandler (this.OnButtonCommaClicked);
			this.button.Clicked += new global::System.EventHandler (this.OnButtonClicked);
			this.buttonPlus.Clicked += new global::System.EventHandler (this.OnButtonPlusClicked);
			this.buttonMinus.Clicked += new global::System.EventHandler (this.OnButtonMinusClicked);
			this.buttonMultiply.Clicked += new global::System.EventHandler (this.OnButtonMultiplyClicked);
			this.buttonDivide.Clicked += new global::System.EventHandler (this.OnButtonDivideClicked);
			this.buttonModulus.Clicked += new global::System.EventHandler (this.OnButtonModulusClicked);
			this.buttonEnter.Clicked += new global::System.EventHandler (this.OnButtonEnterClicked);
		}
	}
}
