
// This file has been generated by the GUI designer. Do not modify.
namespace UltiCalcGUI
{
	public partial class MainWindow
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.HBox hbox1;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Button BMI;
		private global::Gtk.Button IPN;
		private global::Gtk.Button MCon;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Button Savings;
		private global::Gtk.Button Debt;
		private global::Gtk.Button button4;
		private global::Gtk.HBox hbox4;
		private global::Gtk.Button button7;
		private global::Gtk.Button button8;
		private global::Gtk.Button button9;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget UltiCalcGUI.MainWindow
			this.Name = "UltiCalcGUI.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child UltiCalcGUI.MainWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			this.hbox1.BorderWidth = ((uint)(42));
			// Container child hbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.BMI = new global::Gtk.Button ();
			this.BMI.CanFocus = true;
			this.BMI.Name = "BMI";
			this.BMI.UseUnderline = true;
			this.BMI.Label = global::Mono.Unix.Catalog.GetString ("BMI");
			this.hbox2.Add (this.BMI);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.BMI]));
			w1.Position = 0;
			w1.Expand = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.IPN = new global::Gtk.Button ();
			this.IPN.CanFocus = true;
			this.IPN.Name = "IPN";
			this.IPN.UseUnderline = true;
			this.IPN.Label = global::Mono.Unix.Catalog.GetString ("Inverse Polish Notation");
			this.hbox2.Add (this.IPN);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.IPN]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.MCon = new global::Gtk.Button ();
			this.MCon.CanFocus = true;
			this.MCon.Name = "MCon";
			this.MCon.UseUnderline = true;
			this.MCon.Label = global::Mono.Unix.Catalog.GetString ("Measurement Converter");
			this.hbox2.Add (this.MCon);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.MCon]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.hbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.hbox2]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			this.hbox3.BorderWidth = ((uint)(36));
			// Container child hbox3.Gtk.Box+BoxChild
			this.Savings = new global::Gtk.Button ();
			this.Savings.CanFocus = true;
			this.Savings.Name = "Savings";
			this.Savings.UseUnderline = true;
			this.Savings.Label = global::Mono.Unix.Catalog.GetString ("Savings");
			this.hbox3.Add (this.Savings);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.Savings]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.Debt = new global::Gtk.Button ();
			this.Debt.CanFocus = true;
			this.Debt.Name = "Debt";
			this.Debt.UseUnderline = true;
			this.Debt.Label = global::Mono.Unix.Catalog.GetString ("Debt");
			this.hbox3.Add (this.Debt);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.Debt]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.button4 = new global::Gtk.Button ();
			this.button4.CanFocus = true;
			this.button4.Name = "button4";
			this.button4.UseUnderline = true;
			this.button4.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
			this.hbox3.Add (this.button4);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.button4]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			this.vbox1.Add (this.hbox3);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			this.hbox4.BorderWidth = ((uint)(36));
			// Container child hbox4.Gtk.Box+BoxChild
			this.button7 = new global::Gtk.Button ();
			this.button7.CanFocus = true;
			this.button7.Name = "button7";
			this.button7.UseUnderline = true;
			this.button7.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
			this.hbox4.Add (this.button7);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.button7]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.button8 = new global::Gtk.Button ();
			this.button8.CanFocus = true;
			this.button8.Name = "button8";
			this.button8.UseUnderline = true;
			this.button8.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
			this.hbox4.Add (this.button8);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.button8]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.button9 = new global::Gtk.Button ();
			this.button9.CanFocus = true;
			this.button9.Name = "button9";
			this.button9.UseUnderline = true;
			this.button9.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
			this.hbox4.Add (this.button9);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.button9]));
			w12.Position = 2;
			w12.Expand = false;
			w12.Fill = false;
			this.vbox1.Add (this.hbox4);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox4]));
			w13.Position = 2;
			w13.Expand = false;
			w13.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 451;
			this.DefaultHeight = 500;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.BMI.Clicked += new global::System.EventHandler (this.OnBMIClicked);
			this.IPN.Clicked += new global::System.EventHandler (this.OnIPNClicked);
			this.MCon.Clicked += new global::System.EventHandler (this.OnMConClicked);
			this.Savings.Clicked += new global::System.EventHandler (this.OnSavingsClicked);
			this.Debt.Clicked += new global::System.EventHandler (this.OnDebtClicked);
		}
	}
}
