
// This file has been generated by the GUI designer. Do not modify.
namespace UltiCalcGUI
{
	public partial class BMIWindow
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget UltiCalcGUI.BMIWindow
			this.Name = "UltiCalcGUI.BMIWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("BMIWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
