
// This file has been generated by the GUI designer. Do not modify.
namespace UltiCalcGUI
{
	public partial class theBMIWindow
	{
		private global::Gtk.VBox vbox6;
		private global::Gtk.HBox hbox6;
		private global::Gtk.Label label9;
		private global::Gtk.Entry num1;
		private global::Gtk.HBox hbox7;
		private global::Gtk.Label label10;
		private global::Gtk.Entry num2;
		private global::Gtk.VBox vbox9;
		private global::Gtk.VBox vbox10;
		private global::Gtk.HBox hbox11;
		private global::Gtk.Label label11;
		private global::Gtk.Entry num3;
		private global::Gtk.Label lab1;
		private global::Gtk.HBox hbox12;
		private global::Gtk.Button button1;
		private global::Gtk.Button button2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget UltiCalcGUI.theBMIWindow
			this.Name = "UltiCalcGUI.theBMIWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("theBMIWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child UltiCalcGUI.theBMIWindow.Gtk.Container+ContainerChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Height (cm):");
			this.hbox6.Add (this.label9);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label9]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.num1 = new global::Gtk.Entry ();
			this.num1.CanFocus = true;
			this.num1.Name = "num1";
			this.num1.IsEditable = true;
			this.num1.InvisibleChar = '●';
			this.hbox6.Add (this.num1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.num1]));
			w2.Position = 1;
			this.vbox6.Add (this.hbox6);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox6]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Weight (kg):");
			this.hbox7.Add (this.label10);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.label10]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.num2 = new global::Gtk.Entry ();
			this.num2.CanFocus = true;
			this.num2.Name = "num2";
			this.num2.IsEditable = true;
			this.num2.InvisibleChar = '●';
			this.hbox7.Add (this.num2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.num2]));
			w5.Position = 1;
			this.vbox6.Add (this.hbox7);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox7]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.vbox9 = new global::Gtk.VBox ();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.vbox10 = new global::Gtk.VBox ();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			// Container child vbox10.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox ();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Your BMI:    ");
			this.hbox11.Add (this.label11);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.label11]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.num3 = new global::Gtk.Entry ();
			this.num3.CanFocus = true;
			this.num3.Name = "num3";
			this.num3.IsEditable = true;
			this.num3.InvisibleChar = '●';
			this.hbox11.Add (this.num3);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.num3]));
			w8.Position = 1;
			this.vbox10.Add (this.hbox11);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.hbox11]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.lab1 = new global::Gtk.Label ();
			this.lab1.Name = "lab1";
			this.vbox10.Add (this.lab1);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.lab1]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.hbox12 = new global::Gtk.HBox ();
			this.hbox12.Name = "hbox12";
			this.hbox12.Spacing = 6;
			// Container child hbox12.Gtk.Box+BoxChild
			this.button1 = new global::Gtk.Button ();
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			this.button1.Label = global::Mono.Unix.Catalog.GetString ("Calculate");
			this.hbox12.Add (this.button1);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.button1]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox12.Gtk.Box+BoxChild
			this.button2 = new global::Gtk.Button ();
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			this.button2.UseUnderline = true;
			this.button2.Label = global::Mono.Unix.Catalog.GetString ("Reset");
			this.hbox12.Add (this.button2);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.button2]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			this.vbox10.Add (this.hbox12);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.hbox12]));
			w13.Position = 2;
			w13.Expand = false;
			w13.Fill = false;
			this.vbox9.Add (this.vbox10);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.vbox10]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			this.vbox6.Add (this.vbox9);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.vbox9]));
			w15.Position = 2;
			w15.Expand = false;
			w15.Fill = false;
			this.Add (this.vbox6);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
			this.button1.Clicked += new global::System.EventHandler (this.OnButton1Clicked);
			this.button2.Clicked += new global::System.EventHandler (this.OnButton2Clicked);
		}
	}
}
